### ISSUE TITLE
Suggetion

### ISSUE THREAD

**Issue by NotStark** [Qewertyy/Open-API#1]
Try raising an error when a method cannot run successfully, for example, when encountering a 'RequestFailed' situation. Another convenient approach could be to provide an error code and message when a request fails, like this: {'code': 400, 'message': 'This service is currently unavailable.'} I know you have already implemented this in the API, but it serves as a backup in case the API experiences downtime.

My suggestion is to raise an error when needed, as you already have the 'code' and 'message' available in the API

**Comment by Qewertyy** [comment]
alright, thanks for the suggestion.
