### ISSUE TITLE
Image generation support.

### ISSUE THREAD

**Issue by raymerjacque** [Qewertyy/Open-API#6]
i notice you have everything except image generation support ? do you plan to add it ?

**Comment by Qewertyy** [comment]
[L118](https://github.com/Qewertyy/LexicaAPI/blob/d95c1b13bf1ef72a67abd9262e7506c35b3d2538/lexica/core.py#L118)
[L152](https://github.com/Qewertyy/LexicaAPI/blob/d95c1b13bf1ef72a67abd9262e7506c35b3d2538/lexica/core.py#L152)
